#index:
#    path: /
#    controller: App\Controller\DefaultController::index
lightsaml_sp:
    resource: "@LightSamlSpBundle/Resources/config/routing.yml"
    prefix: saml

lightsaml_sp.logout:
    path: /saml/logout